name: Python_CI_Final_Fix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install psutil colorama flake8

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m unittest discover .

    - name: Build Docker
      run: |
        docker build -t student-app .